version: 2
updates:
  - package-ecosystem: uv
    directories:
      - /
      - /engine
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
